#define MBEDTLS_X509_CREATE_C
#define MBEDTLS_X509_CRT_WRITE_C
#define MBEDTLS_X509_CSR_WRITE_C
#define MBEDTLS_PEM_WRITE_C

#define MBEDTLS_ECP_RESTARTABLE
#define MBEDTLS_HKDF_C
#define MBEDTLS_ECDH_C
#define MBEDTLS_AES_FEWER_TABLES

//#define MBEDTLS_LMS_C
//#define MBEDTLS_LMS_PRIVATE
